// AutosGPS-GDL/app/login/page.tsx
"use client"

import type React from "react"

import { useState } from "react"
import { useRouter, useSearchParams } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { Alert, AlertDescription } from "@/components/ui/alert"
import Link from "next/link"
import { ArrowLeft } from "lucide-react"

export default function Login() {
  const router = useRouter()
  const searchParams = useSearchParams()
  const role = searchParams.get("role") || ""

  const [email, setEmail] = useState(
    role === "admin_global"
      ? "admin.global@vehiculos.com"
      : role === "admin"
        ? "admin@vehiculos.com"
        : role === "user"
          ? "usuario@vehiculos.com"
          : "",
  )
  const [password, setPassword] = useState(
    role === "admin_global" ? "AdminGlobal@123" : role === "admin" ? "Admin@123" : role === "user" ? "Usuario@123" : "",
  )
  const [error, setError] = useState("")
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    setError("")

    try {
      // Simulación de autenticación
      if (email === "admin.global@vehiculos.com" && password === "AdminGlobal@123") {
        // Redirigir al panel de administrador global
        localStorage.setItem("userRole", "admin_global")
        localStorage.setItem("userId", "1")
        router.push("/admin/dashboard")
      } else if (email === "admin@vehiculos.com" && password === "Admin@123") {
        // Redirigir al panel de administrador normal
        localStorage.setItem("userRole", "admin")
        localStorage.setItem("userId", "2")
        router.push("/admin/dashboard")
      } else if (email === "usuario@vehiculos.com" && password === "Usuario@123") {
        // Redirigir al panel de usuario
        localStorage.setItem("userRole", "usuario")
        localStorage.setItem("userId", "3")
        router.push("/user/dashboard")
      } else {
        setError("Credenciales inválidas. Por favor, intente nuevamente.")
      }
    } catch (err) {
      setError("Error al iniciar sesión. Por favor, intente nuevamente.")
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
      <div className="w-full max-w-md">
        <Link href="/" className="flex items-center text-sm text-gray-600 mb-6 hover:text-gray-900">
          <ArrowLeft className="h-4 w-4 mr-1" />
          Volver al inicio
        </Link>

        <Card>
          <CardHeader>
            <CardTitle>Iniciar Sesión</CardTitle>
            <CardDescription>Ingrese sus credenciales para acceder al sistema</CardDescription>
          </CardHeader>
          <CardContent>
            {error && (
              <Alert variant="destructive" className="mb-4">
                <AlertDescription>{error}</AlertDescription>
              </Alert>
            )}
            <form onSubmit={handleSubmit}>
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="email">Correo electrónico</Label>
                  <Input
                    id="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="correo@ejemplo.com"
                    required
                  />
                </div>
                <div className="grid gap-2">
                  <Label htmlFor="password">Contraseña</Label>
                  <Input
                    id="password"
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    required
                  />
                </div>
              </div>
              <Button className="w-full mt-6" type="submit" disabled={loading}>
                {loading ? "Iniciando sesión..." : "Iniciar sesión"}
              </Button>
            </form>
          </CardContent>
          <CardFooter className="flex flex-col items-center">
            <div className="text-sm text-gray-500 mt-2 space-y-1">
              <p>
                <strong>Admin Global:</strong> admin.global@vehiculos.com / AdminGlobal@123
              </p>
              <p>
                <strong>Admin Normal:</strong> admin@vehiculos.com / Admin@123
              </p>
              <p>
                <strong>Usuario:</strong> usuario@vehiculos.com / Usuario@123
              </p>
            </div>
          </CardFooter>
        </Card>
      </div>
    </div>
  )
}

// src/views/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          🔐 Iniciar Sesión
        </h2>
        <p class="mt-2 text-center text-sm text-gray-600">
          Sistema de Gestión de Vehículos
        </p>
      </div>
      
      <form class="mt-8 space-y-6" @submit.prevent="handleLogin">
        <div class="rounded-md shadow-sm -space-y-px">
          <div>
            <label for="email" class="sr-only">Email</label>
            <input
              id="email"
              v-model="form.email"
              name="email"
              type="email"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
              placeholder="Correo electrónico (@gmail.com)"
            />
          </div>
          <div>
            <label for="password" class="sr-only">Contraseña</label>
            <input
              id="password"
              v-model="form.password"
              name="password"
              type="password"
              required
              class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
              placeholder="Contraseña"
            />
          </div>
        </div>

        <div>
          <button
            type="submit"
            :disabled="loading"
            class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
          >
            <span v-if="loading" class="spinner w-4 h-4 mr-2"></span>
            {{ loading ? 'Iniciando...' : 'Iniciar Sesión' }}
          </button>
        </div>

        <div class="mt-6">
          <div class="text-sm text-gray-600">
            <h3 class="font-medium mb-2">📧 Usuarios de prueba:</h3>
            <div class="space-y-1 text-xs">
              <p><strong>Admin Global:</strong> admin.global@gmail.com / AdminGlobal@123</p>
              <p><strong>Admin:</strong> admin@gmail.com / Admin@123</p>
              <p><strong>Usuario:</strong> usuario@gmail.com / Usuario@123</p>
            </div>
          </div>
        </div>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue"
import { useRouter } from "vue-router"
import { useAuthStore } from "@/stores/auth"

const router = useRouter()
const authStore = useAuthStore()

const form = ref({
  email: "",
  password: "",
})

const loading = ref(false)

const handleLogin = async () => {
  loading.value = true
  
  const success = await authStore.login(form.value.email, form.value.password)
  
  if (success) {
    if (authStore.isAdmin) {
      router.push("/admin/dashboard")
    } else {
      router.push("/user/dashboard")
    }
  }
  
  loading.value = false
}
</script>
