// AutosGPS-GDL/app/user/perfil/page.tsx
"use client"

import type React from "react"

import { useState } from "react"
import UserLayout from "@/components/user-layout"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { User, Camera, Lock } from "lucide-react"

export default function UserPerfil() {
  const [nombre, setNombre] = useState("María")
  const [apellido, setApellido] = useState("Rodríguez")
  const [telefono, setTelefono] = useState("+34 612 345 678")
  const [currentPassword, setCurrentPassword] = useState("")
  const [newPassword, setNewPassword] = useState("")
  const [confirmPassword, setConfirmPassword] = useState("")
  const [passwordError, setPasswordError] = useState("")
  const [successMessage, setSuccessMessage] = useState("")

  const validatePassword = (password: string) => {
    const hasUpperCase = /[A-Z]/.test(password)
    const hasLowerCase = /[a-z]/.test(password)
    const hasNumber = /[0-9]/.test(password)
    const hasSpecialChar = /[!@#$%^&*()_+\-=[\]{};':"\\|,.<>/?]/.test(password)
    const isLongEnough = password.length >= 8

    if (!hasUpperCase || !hasLowerCase || !hasNumber || !hasSpecialChar || !isLongEnough) {
      setPasswordError(
        "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial.",
      )
      return false
    }

    setPasswordError("")
    return true
  }

  const handleProfileUpdate = (e: React.FormEvent) => {
    e.preventDefault()
    setSuccessMessage("Perfil actualizado correctamente")
    setTimeout(() => setSuccessMessage(""), 3000)
  }

  const handlePasswordChange = (e: React.FormEvent) => {
    e.preventDefault()

    if (newPassword !== confirmPassword) {
      setPasswordError("Las contraseñas no coinciden")
      return
    }

    if (!validatePassword(newPassword)) {
      return
    }

    setSuccessMessage("Contraseña cambiada correctamente")
    setCurrentPassword("")
    setNewPassword("")
    setConfirmPassword("")
    setTimeout(() => setSuccessMessage(""), 3000)
  }

  return (
    <UserLayout>
      <div className="grid gap-6 max-w-4xl">
        <h1 className="text-3xl font-bold">Mi Perfil</h1>

        {successMessage && (
          <Alert className="border-green-200 bg-green-50">
            <AlertDescription className="text-green-800">{successMessage}</AlertDescription>
          </Alert>
        )}

        <Tabs defaultValue="perfil" className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="perfil">Información Personal</TabsTrigger>
            <TabsTrigger value="password">Cambiar Contraseña</TabsTrigger>
          </TabsList>

          <TabsContent value="perfil">
            <Card>
              <CardHeader>
                <CardTitle>Información Personal</CardTitle>
                <CardDescription>Actualiza tu información personal y foto de perfil</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="flex items-center space-x-4">
                  <Avatar className="w-20 h-20">
                    <AvatarImage src="/placeholder.svg?height=80&width=80" />
                    <AvatarFallback>
                      <User className="w-8 h-8" />
                    </AvatarFallback>
                  </Avatar>
                  <Button variant="outline">
                    <Camera className="w-4 h-4 mr-2" />
                    Cambiar Foto
                  </Button>
                </div>

                <form onSubmit={handleProfileUpdate} className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="nombre">Nombre</Label>
                      <Input id="nombre" value={nombre} onChange={(e) => setNombre(e.target.value)} required />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="apellido">Apellido</Label>
                      <Input id="apellido" value={apellido} onChange={(e) => setApellido(e.target.value)} required />
                    </div>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="email">Correo Electrónico</Label>
                    <Input id="email" type="email" value="usuario@vehiculos.com" disabled />
                    <p className="text-sm text-gray-500">El correo electrónico no se puede modificar</p>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="telefono">Teléfono</Label>
                    <Input id="telefono" value={telefono} onChange={(e) => setTelefono(e.target.value)} />
                  </div>

                  <Button type="submit">Guardar Cambios</Button>
                </form>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="password">
            <Card>
              <CardHeader>
                <CardTitle>Cambiar Contraseña</CardTitle>
                <CardDescription>Actualiza tu contraseña para mantener tu cuenta segura</CardDescription>
              </CardHeader>
              <CardContent>
                {passwordError && (
                  <Alert variant="destructive" className="mb-4">
                    <AlertDescription>{passwordError}</AlertDescription>
                  </Alert>
                )}

                <form onSubmit={handlePasswordChange} className="space-y-4">
                  <div className="space-y-2">
                    <Label htmlFor="currentPassword">Contraseña Actual</Label>
                    <Input
                      id="currentPassword"
                      type="password"
                      value={currentPassword}
                      onChange={(e) => setCurrentPassword(e.target.value)}
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="newPassword">Nueva Contraseña</Label>
                    <Input
                      id="newPassword"
                      type="password"
                      value={newPassword}
                      onChange={(e) => {
                        setNewPassword(e.target.value)
                        if (e.target.value) validatePassword(e.target.value)
                      }}
                      required
                    />
                    <p className="text-xs text-gray-500">
                      Debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial
                    </p>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="confirmPassword">Confirmar Nueva Contraseña</Label>
                    <Input
                      id="confirmPassword"
                      type="password"
                      value={confirmPassword}
                      onChange={(e) => setConfirmPassword(e.target.value)}
                      required
                    />
                  </div>

                  <Button type="submit">
                    <Lock className="w-4 h-4 mr-2" />
                    Cambiar Contraseña
                  </Button>
                </form>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>
    </UserLayout>
  )
}

// src/views/user/Perfil.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <h1 class="text-3xl font-bold text-gray-900">👤 Mi Perfil</h1>
    </div>

    <!-- Información Personal -->
    <div class="bg-white rounded-lg shadow p-6">
      <h2 class="text-xl font-semibold text-gray-900 mb-4">📝 Información Personal</h2>
      <form @submit.prevent="actualizarPerfil" class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Nombre</label>
          <input
            v-model="perfil.nombre"
            type="text"
            required
            class="form-input"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Apellido</label>
          <input
            v-model="perfil.apellido"
            type="text"
            required
            class="form-input"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Email</label>
          <input
            v-model="perfil.email"
            type="email"
            disabled
            class="form-input bg-gray-100 cursor-not-allowed"
          />
          <p class="text-xs text-gray-500 mt-1">El email no se puede modificar</p>
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Teléfono (10 dígitos)</label>
          <input
            v-model="perfil.telefono"
            type="tel"
            maxlength="10"
            class="form-input"
            placeholder="3312345678"
          />
        </div>
        
        <div class="md:col-span-2">
          <label class="block text-sm font-medium text-gray-700 mb-1">Foto de Perfil</label>
          <input
            @change="manejarFoto"
            type="file"
            accept="image/*"
            class="form-input"
          />
          <div v-if="perfil.foto" class="mt-2">
            <img :src="perfil.foto" alt="Foto de perfil" class="w-20 h-20 rounded-full object-cover" />
          </div>
        </div>
        
        <div class="md:col-span-2">
          <button
            type="submit"
            class="btn-success"
          >
            ✅ Actualizar Perfil
          </button>
        </div>
      </form>
    </div>

    <!-- Cambiar Contraseña -->
    <div class="bg-white rounded-lg shadow p-6">
      <h2 class="text-xl font-semibold text-gray-900 mb-4">🔒 Cambiar Contraseña</h2>
      <form @submit.prevent="cambiarContrasena" class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Contraseña Actual</label>
          <input
            v-model="cambioContrasena.actual"
            type="password"
            required
            class="form-input"
          />
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Nueva Contraseña</label>
          <input
            v-model="cambioContrasena.nueva"
            type="password"
            required
            class="form-input"
          />
          <p class="text-xs text-gray-500 mt-1">Mínimo 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial</p>
        </div>
        
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Confirmar Nueva Contraseña</label>
          <input
            v-model="cambioContrasena.confirmar"
            type="password"
            required
            class="form-input"
          />
        </div>
        
        <button
          type="submit"
          class="btn-primary"
        >
          🔐 Cambiar Contraseña
        </button>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue"
import { useAuthStore } from "@/stores/auth"
import { useToast } from "vue-toastification"

const authStore = useAuthStore()
const toast = useToast()

const perfil = ref({
  nombre: "",
  apellido: "",
  email: "",
  telefono: "",
  foto: null,
})

const cambioContrasena = ref({
  actual: "",
  nueva: "",
  confirmar: "",
})

const manejarFoto = (event) => {
  const file = event.target.files[0]
  if (file) {
    const reader = new FileReader()
    reader.onload = (e) => {
      perfil.value.foto = e.target.result
    }
    reader.readAsDataURL(file)
  }
}

const actualizarPerfil = () => {
  // ✅ Validar teléfono si se proporciona
  if (perfil.value.telefono && !authStore.validarTelefono(perfil.value.telefono)) {
    toast.error("❌ El teléfono debe tener exactamente 10 dígitos")
    return
  }

  // Guardar en localStorage
  const perfilActualizado = { ...perfil.value }
  localStorage.setItem("perfil_usuario", JSON.stringify(perfilActualizado))

  toast.success("✅ Perfil actualizado correctamente")
}

const cambiarContrasena = () => {
  // ✅ Validar que la nueva contraseña sea diferente
  if (cambioContrasena.value.actual === cambioContrasena.value.nueva) {
    toast.error("❌ La nueva contraseña debe ser diferente a la actual")
    return
  }

  // ✅ Validar nueva contraseña
  if (!authStore.validarContrasena(cambioContrasena.value.nueva)) {
    toast.error("❌ La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial")
    return
  }

  // ✅ Validar confirmación
  if (cambioContrasena.value.nueva !== cambioContrasena.value.confirmar) {
    toast.error("❌ Las contraseñas no coinciden")
    return
  }

  // Limpiar formulario
  cambioContrasena.value = {
    actual: "",
    nueva: "",
    confirmar: "",
  }

  toast.success("✅ Contraseña cambiada correctamente")
}

onMounted(() => {
  // Cargar datos del usuario actual
  const user = authStore.user
  if (user) {
    perfil.value = {
      nombre: user.nombre,
      apellido: user.apellido,
      email: user.email,
      telefono: user.telefono,
      foto: user.foto,
    }
  }

  // Cargar perfil guardado si existe
  const perfilGuardado = localStorage.getItem("perfil_usuario")
  if (perfilGuardado) {
    const datos = JSON.parse(perfilGuardado)
    perfil.value = { ...perfil.value, ...datos }
  }
})
</script>
