// AutosGPS-GDL/app/user/vehiculos/page.tsx
"use client"
import UserLayout from "@/components/user-layout"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { vehiculosData } from "@/lib/data"

// Simular que el usuario actual tiene ID 2
const USUARIO_ACTUAL_ID = 2

export default function UserVehiculos() {
  // Filtrar vehículos asignados al usuario actual
  const vehiculosUsuario = vehiculosData.filter((v) => v.usuarioId === USUARIO_ACTUAL_ID)

  return (
    <UserLayout>
      <div className="grid gap-6">
        <h1 className="text-3xl font-bold">Mis Vehículos</h1>

        {vehiculosUsuario.length === 0 ? (
          <Card>
            <CardContent className="p-6 text-center">
              <p className="text-gray-500">No tienes vehículos asignados actualmente.</p>
            </CardContent>
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {vehiculosUsuario.map((vehiculo) => (
              <Card key={vehiculo.id} className="overflow-hidden">
                <div className="aspect-video bg-gray-100 relative">
                  <img
                    src={vehiculo.imagen || "/placeholder.svg?height=200&width=400"}
                    alt={`${vehiculo.marca} ${vehiculo.modelo}`}
                    className="w-full h-full object-cover"
                  />
                  <Badge className="absolute top-2 right-2 bg-green-500">Asignado</Badge>
                </div>
                <CardHeader>
                  <div className="flex justify-between items-start">
                    <CardTitle>
                      {vehiculo.marca} {vehiculo.modelo}
                    </CardTitle>
                    <Badge variant="outline">{vehiculo.matricula}</Badge>
                  </div>
                </CardHeader>
                <CardContent>
                  <Tabs defaultValue="detalles">
                    <TabsList className="grid w-full grid-cols-2">
                      <TabsTrigger value="detalles">Detalles</TabsTrigger>
                      <TabsTrigger value="ubicacion">Ubicación</TabsTrigger>
                    </TabsList>
                    <TabsContent value="detalles" className="space-y-2 mt-4">
                      <div className="grid grid-cols-2 gap-2">
                        <div>
                          <p className="text-sm font-medium">Año</p>
                          <p className="text-sm text-gray-500">{vehiculo.anio}</p>
                        </div>
                        <div>
                          <p className="text-sm font-medium">Tipo</p>
                          <p className="text-sm text-gray-500">{vehiculo.tipo}</p>
                        </div>
                        <div>
                          <p className="text-sm font-medium">Color</p>
                          <p className="text-sm text-gray-500">{vehiculo.color}</p>
                        </div>
                        <div>
                          <p className="text-sm font-medium">Estado</p>
                          <p className="text-sm text-gray-500">Activo</p>
                        </div>
                      </div>
                    </TabsContent>
                    <TabsContent value="ubicacion" className="mt-4">
                      <div className="bg-gray-100 rounded-md h-[150px] flex items-center justify-center">
                        <p className="text-sm text-gray-500">Mapa de ubicación (solo visualización)</p>
                      </div>
                      <div className="mt-2 text-xs text-gray-500">
                        <p>Última actualización: hace {Math.floor(Math.random() * 60) + 1} minutos</p>
                        <p>Lat: {(40.416775 + (Math.random() * 0.1 - 0.05)).toFixed(6)}</p>
                        <p>Lng: {(-3.70379 + (Math.random() * 0.1 - 0.05)).toFixed(6)}</p>
                      </div>
                    </TabsContent>
                  </Tabs>
                </CardContent>
              </Card>
            ))}
          </div>
        )}
      </div>
    </UserLayout>
  )
}

// src/views/user/Vehiculos.vue
<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <h1 class="text-3xl font-bold text-gray-900">🚗 Mis Vehículos</h1>
    </div>

    <!-- Mis vehículos asignados -->
    <div class="bg-white rounded-lg shadow p-6">
      <h2 class="text-xl font-semibold text-gray-900 mb-4">📋 Vehículos Asignados</h2>
      <div v-if="misVehiculos.length === 0" class="text-center py-12">
        <span class="text-6xl">🚫</span>
        <h3 class="text-xl font-medium text-gray-900 mt-4">No tienes vehículos asignados</h3>
        <p class="text-gray-500 mt-2">Contacta al administrador para solicitar la asignación de un vehículo</p>
      </div>
      <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div v-for="vehiculo in misVehiculos" :key="vehiculo.id" class="border rounded-lg p-4 hover:shadow-lg transition-shadow">
          <div class="aspect-w-16 aspect-h-9 mb-4">
            <img 
              :src="vehiculo.imagen || '/placeholder.svg?height=200&width=300'" 
              :alt="vehiculo.marca + ' ' + vehiculo.modelo"
              class="w-full h-48 object-cover rounded-lg"
            />
          </div>
          <div class="space-y-2">
            <h3 class="text-lg font-semibold">{{ vehiculo.marca }} {{ vehiculo.modelo }}</h3>
            <p class="text-sm text-gray-600">📅 Año: {{ vehiculo.ano }}</p>
            <p class="text-sm text-gray-600">🔢 Matrícula: {{ vehiculo.matricula }}</p>
            <p class="text-sm text-gray-600">🚙 Tipo: {{ vehiculo.tipo }}</p>
            <p class="text-sm text-gray-600">🎨 Color: {{ vehiculo.color }}</p>
            <div class="flex items-center justify-between">
              <span class="px-2 py-1 text-xs font-medium bg-yellow-100 text-yellow-800 rounded-full">
                📋 Asignado a mí
              </span>
              <div class="text-xs text-gray-500">
                📍 Lat: {{ vehiculo.latitud?.toFixed(4) }}<br>
                📍 Lng: {{ vehiculo.longitud?.toFixed(4) }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Información adicional -->
    <div class="bg-blue-50 border border-blue-200 rounded-lg p-4">
      <div class="flex">
        <div class="flex-shrink-0">
          <span class="text-2xl">ℹ️</span>
        </div>
        <div class="ml-3">
          <h3 class="text-sm font-medium text-blue-800">Información</h3>
          <div class="mt-2 text-sm text-blue-700">
            <p>• Puedes ver la ubicación en tiempo real de tus vehículos en el mapa GPS</p>
            <p>• Los vehículos se actualizan automáticamente cada 30 segundos</p>
            <p>• Para solicitar cambios en las asignaciones, contacta al administrador</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue"
import { useAuthStore } from "@/stores/auth"

const authStore = useAuthStore()
const misVehiculos = ref([])

onMounted(() => {
  // Cargar vehículos asignados al usuario actual
  const vehiculos = JSON.parse(localStorage.getItem("vehiculos") || "[]")
  const asignaciones = JSON.parse(localStorage.getItem("asignaciones") || "[]")
  
  // Filtrar vehículos asignados al usuario actual
  const asignacionesUsuario = asignaciones.filter(a => 
    a.usuarioId === authStore.user?.email && a.activa
  )
  
  misVehiculos.value = vehiculos.filter(v => 
    asignacionesUsuario.some(a => a.vehiculoId === v.id)
  )
})
</script>
